### ISSUE TITLE
Request to take over

### ISSUE THREAD

**Issue by dvershinin** [Ipstenu/varnish-http-purge#103]
Hi Mika,

I actively use Varnish and have a performance-oriented blog at www.getpagespeed.com with some articles like [this](https://www.getpagespeed.com/server-setup/varnish/accelerate-wordpress-with-varnish-cache) touching on Varnish, NGINX, etc.

Your plugin is actually dependency for my small plugin I have that warms up the cache after purge. See [Cacheability](https://wordpress.org/plugins/cacheability/). 

Fork created at https://github.com/dvershinin/varnish-http-purge

**Comment by Ipstenu** [comment]
@dvershinin Works for me. I added `dvershinin` to [the WP plugin](https://wordpress.org/plugins/varnish-http-purge) and removed myself :) Consider this yours! Enjoy!

I would recommend updating the FAQ (Don’t you work at DreamHost? Is this Official or DreamHost only?) and removing the DH logo from the banner. Since DreamHost isn't using it anymore, I doubt they really care.
