### ISSUE TITLE
Unable to find a caching service active for this domain.

### ISSUE THREAD

**Issue by stafca159** [Ipstenu/varnish-http-purge#91]
Hi,
In sitediagnose I get the following error message about the Proxy Cache Purge Plugin.

'Cache Service: Site: https://example.com
We were unable find a caching service active for this domain. This may occur if you use a proxy service (such as CloudFlare or Sucuri) or if you're in the middle of a DNS move.'

Situation: I am not using Cloudflare, not in a DNS move and the IP address of the Varnish Cache is inserted.

Question: is this a bug or is this expected behavior?

Thanks for feedback.

**Comment by Ipstenu** [comment]
That greatly depends on what cache you think it is. If it's literally example.com, then no, not a bug. If it's your domain then it means whatever data the server sends back doesn't match the known metrics for the plugin so ... maybe? Without knowing the domain you're checking, I cannot say for sure.

**Comment by stafca159** [comment]
Hi,

Thank you for your reply.
It’s conc. Varnish v.4 cache on domain anita fleerackers.be

Thank you for feedback.

Best regards,
Staf
__________________________________
Staf Campforts
Hemeldonk 9
B-2275 Gierle Belgium
mob; +32 (0)497 47 07 82
email: ***@***.***
www.anitafleerackers.be

Please consider your environmental responsibility before printing this email.

**Comment by Ipstenu** [comment]
So the checker is correct. Your server is not returning proper Varnish headers.

```
HTTP/1.1 200 OK
--
Server: | nginx
Date: | Mon, 31 May 2021 17:40:32 GMT
Content-Type: | text/html; charset=UTF-8
Content-Length: | 22257
Connection: | keep-alive
X-Content-Security-Policy: [snipped]
Content-Security-Policy: [snipped]
Strict-Transport-Security: | max-age=63072000; includeSubDomains; preload
X-Frame-Options: | SAMEORIGIN
Cache-Control: | max-age=0
Expires: | Mon, 31 May 2021 17:39:01 GMT
Vary: | Accept-Encoding
Content-Encoding: | gzip
X-XSS-Protection: | 1; mode=block
X-Content-Type-Options: | nosniff
Referrer-Policy: | no-referrer-when-downgrade
Permissions-Policy: | interest-cohort=()
Age: | 88
Accept-Ranges: | bytes
```

At the very least there should be an X-Varnish: header, or a Via header that is equal to Varnish (sometimes it has the version of Varnish)

The 'easiest' way to test would be to run `curl -I https://YOURDOMAIN.COM` and check the response.

I will note you also have `cache-control: max-age=0` which will cause most cache services to not cache, since that tells is "The oldest this page can be is 0 seconds old." which translates to ... never :(
